---

language: bash

env:
  global:
    - BASEBOX_VERSION="0.0.1"
    - PACKER_VERSION="0.12.2"
    - secure: "lU4478HsKTBv/nb8zU3TqDbRBveSZGh97aEoQBoeSgdOe2ngNy+vAqljQI1P6v2SKue7CzCPI2QlLirJe1KaimpBQOq557VwDZt2RbNLOVM1i3qqMC2e5hJjyY1UPI4jhJu94xuGdi239M5ji7EVvIRig1bCEqVYpA0vlypxWfO74xUtR2+j1GqkecnbsAq4Iiu5ycx9lGyKtLVCiV5WnGb7rwueH7RnVgtF44Lo0u/017xAVK5+IRtfwB+cE7tq89y4qWmOvrrv5quiTcgdUfe1ilUvA224Bere0wDVDdPU0F9ARFodSZghA+BS+EpONpugzLyaKW/EwcqWzX357mDuy+D3e4MPk9h1t7jr1Ad7+eOWFK4hn4yPeE/gJNmO3yER5BjISHzBbq4oRQg/xOrciLOwvWe8ZNpdhMIePjhAVqlDhFJOKPKM3BPsdu+7KVHFjNgVUk+9gsRq/1Gpv4n+WguD8CQNNEH7zCNHP1xUsO8eVn8hXV5drqaH5/ZNj89aGzWlPoCCS1F+5JXVitLJ4G1HuwmG4K3zJY/upkXSZdOmFWwRMwzA4T1D/mt/84bHVI9Mvox0tUG7QJ1zoMUgrZ1zSZwySt+n9x0wKPZatbaUaybEyEP3BV98Q25FrKzzMUSDNwDfJ5mkGUDANQ9FcEKebZsEARL0Hl99Wfk="
    - secure: "CkopIJxR0gGUpNsDiuRl+xAjV4xmI9zFYlNFqX3n22WR/m/JYN5vxmSq3P11PxchMHLiIUv4R5jZ5SH03zeWsf4UTjnRloKU6k27f8HT75rGKBqMgAlfGoXZ02fq0/IgBy0EiFAM8pW5BN3ymsGaMCo1ZdcQpyaVnlZowwinml7BEZ69xSMxfDt33/tXL6g8mdxUPwIjsOHuTmyz766rI91LZKqnn7UuUNBpfrowfWHvq0WnDhk/WBR5FXvssGRuxc3lWLMs+Z6wlW5flTsbya+Z7s31pxxyMh5LwQe0iF/PEqhDrH+YcNCVaQs04S8CDnXacFHBkfrBqlSnUmQjeSAuQydK8QRQ4IFKJENwFpd0cCEYl7AMIAala1Sm8Uc2O9JKMPzYuJKtL4HhxAqMW2EVsVw7As3yw3fQbg56Ifnq9CcDBJGkwYVJ70de4Dt12zpl/3lyIVawhiRmpyUplhPjZj78GxVE+tlZKpLtElMmkWFo13x+EC/1KMoXKKLfoFzru+ka42GdnpsI7voZ9izUmE95nKk8xQWaT+DwxZyyzFVPr75mmn7XVxso88cNW0WFNIX5/mfDJR9CQ6y0QOopIyzjMqVwNGAqF/Ox/pnXOdpIOL+GzYYmnEdLQ1gkfhLQ7OJYgR3eTbdcsTDMBH3ERIhJrlhcmmoShePLM30="
  matrix:
    - DISTRO=centos6 INIT="/sbin/init"

services:
  - docker

before_install:
  - curl -o /tmp/packer.zip -L "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
  - sudo unzip -o -d /usr/local/bin /tmp/packer.zip
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

before_script:
  - CONTAINER_ID=$(mktemp)
  - IDEMPOTENCE=$(mktemp)

script:
  - scripts/packer docker-centos6 ${DOCKER_USERNAME}
  - 'docker run --detach ${DOCKER_USERNAME}/basebox-centos6:${BASEBOX_VERSION} "${INIT}" > "${CONTAINER_ID}"'
  - tests/validate-results.sh $DISTRO $CONTAINER_ID

notifications:
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_success: change
    on_failure: change
